"""Compatibility proxy for cipher_engine.core.robust."""

from cipher_engine.core.robust import (
    DELTA_MODULATION,
    HEADER_BITS,
    HEADER_BLOCKS,
    HEADER_REP,
    MAGIC_ROBUST,
    MAX_SAFE_DIM,
    RS_PARITY_BYTES,
    bits_to_bytes,
    bytes_to_bits,
    dct2,
    decode,
    decode_image,
    decode_image_bytes,
    encode,
    encode_image,
    idct2,
    max_robust_capacity_bytes,
)

__all__ = [
    "DELTA_MODULATION",
    "HEADER_BITS",
    "HEADER_BLOCKS",
    "HEADER_REP",
    "MAGIC_ROBUST",
    "MAX_SAFE_DIM",
    "RS_PARITY_BYTES",
    "bits_to_bytes",
    "bytes_to_bits",
    "dct2",
    "decode",
    "decode_image",
    "decode_image_bytes",
    "encode",
    "encode_image",
    "idct2",
    "max_robust_capacity_bytes",
]
