"""Compatibility proxy for cipher_engine.core.stego."""

from cipher_engine.core import crypto, lsb, prng
from cipher_engine.core.stego import (
    HEADER_SIZE,
    MAGIC,
    MAGIC_LEN,
    MAGIC_V1,
    ZSTD_HEADER_PREFIX,
    _embed_bytes,
    _extract_bytes,
    _get_slot_indices,
    _normalize_image,
    bits_to_bytes,
    bytes_to_bits,
    bytes_to_chunked_bits,
    chunked_bits_to_bytes,
    decode,
    encode,
    pack_payload,
    unpack_payload,
)

__all__ = [
    "HEADER_SIZE",
    "MAGIC",
    "MAGIC_LEN",
    "MAGIC_V1",
    "ZSTD_HEADER_PREFIX",
    "_embed_bytes",
    "_extract_bytes",
    "_get_slot_indices",
    "_normalize_image",
    "bits_to_bytes",
    "bytes_to_bits",
    "bytes_to_chunked_bits",
    "chunked_bits_to_bytes",
    "crypto",
    "decode",
    "encode",
    "lsb",
    "pack_payload",
    "prng",
    "unpack_payload",
]
